project:
  type: website

website:
  title: "structural"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: MLE.qmd
        text: Maximum Likelihood Estimation
      - href: GMM.qmd
        text: Generalized Method of Moments
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



